version: "3"
services:
  postgres1:
    image: postgres:15.1
    restart: always
    volumes: 
      - db1:/var/lib/postgresql/data
      - ./db/posts.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - "7432:5432"
  postgres2:
    image: postgres:15.1
    restart: always
    volumes: 
      - db2:/var/lib/postgresql/data
      - ./db/threads.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - "8432:5432"
volumes:
  db1:
    driver: local
  db2:
    driver: local
